### ISSUE TITLE
メッセージ部分、下に行くほど文字が上の線に寄っていく。

### ISSUE THREAD

**Issue by soundkitchen** [ahchan9/mariko_yoshimura#4]
PC / SP 両方で確認しました。
ブラウザに寄って寄り具合に差はあるものの、どれも下に行くほど徐々に上に寄っていってしまうようです。

**Comment by ahchan9** [comment]
これか…一応認識していつつもまぁ後でやるかと置いてました;
時間見つけてやります!

**Comment by ahchan9** [comment]
@soundkitchen 
調整しました！どうでしょう？
https://ahchan9.github.io/mariko_yoshimura/

**Comment by soundkitchen** [comment]
@ahchan9 きれいになってました！ありがとー！
本番にもアップしておきました！
